version: '3'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Baum123456
      MYSQL_DATABASE: DevOpsExamDB
      MYSQL_USER: DBuser
      MYSQL_PASSWORD: Baum123456
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  k6:
    image: loadimpact/k6
    volumes:
      - ./path/to/k6/scripts:/scripts
    command: run /scripts/api-test.js


  web:
    build: .
    ports:
      - "7077:7077"
    depends_on:
      - db
    command: ["dotnet", "DevOpsExamApi.csproj"]
    environment:
      - ConnectionStrings__Default=server=db;database=DevOpsExam;uid=massasoftuser;password=password
volumes:
  db_data:
