version: '3'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: Massasoft
      MYSQL_USER: massasoftuser
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
  web:
    build: .
    ports:
      - "443:443"
    depends_on:
      - db
    command: ["dotnet", "MassasoftApi.csproj"]
    environment:
      - ConnectionStrings__Default=server=db;database=Massasoft;uid=massasoftuser;password=password
volumes:
  db_data:
